---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:        
  name: inventree-data
  namespace: inventree
spec:  
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi
...
